name: Feature request
description: Suggest an idea for this project 💡
title: "Feature: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Current behavior
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Desired solution
      description: Describe the solution you'd like.
    validations:
      required: true
